logging:
  level:
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: DEBUG

server:
  shutdown: graceful

spring:
  application:
    name: 'scheduler-jobrunr'
  profiles:
    active:
      - ${SPRING_PROFILE_NAME:dev}
      # - persistent
      - ram
      # - streaming
      - pagination
      # - clustered
      - standalone
  lifecycle:
    timeout-per-shutdown-phase: 4m
  main:
    banner-mode: off
  mvc:
    converters:
      preferred-json-mapper: jackson
  docker:
    compose:
      enabled: true
      file: scheduler-jobrunr/docker-compose.yaml
  datasource:
    username: ${DB_USERNAME:dbusername}
    password: ${DB_PASSWORD:dbpassword}
    url: ${DB_URL:jdbc:postgresql://localhost:5433/db_marketplace_jobrunr}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 5000
      validation-timeout: 2000
      leak-detection-threshold: 300000
  liquibase:
    changelog: classpath:/db/changelog/changelog.yaml
  kafka:
    producer:
      bootstrap-servers: localhost:29093
      client-id: scheduler-comparison-jobrunr-1

org:
  jobrunr:
    jobs:
      default-number-of-retries: 0
    background-job-server:
      enabled: true
      metrics:
        enabled: true
      thread-type: platformthreads
    dashboard:
      enabled: true
    miscellaneous:
      allow-anonymous-data-usage: false

kafka:
  topics:
    notification-platform: order-statuses-jobrunr.1
    loca-lola-refunds: loca-lola-refunds-jobrunr.1

scheduler:
  jobs:
    dedicated-merchant-jobs:
      - name: "Loca-Lola failure refunds"
        merchant-ids: [4]
        order-statuses: [FAILED]
        cron: "0 */1 * * * *"
        # Since this action does not intersect with the other flow, it can be executed concurrently.
        ignored-by-common: false
        max-count-per-execution: 30
        page-size: 10
      - name: "WildFruit handler"
        merchant-ids: [5]
        order-statuses: [PAID, DELIVERED, FAILED, CANCELLED]
        cron: "0 */1 * * * *"
        max-count-per-execution: 30
        page-size: 10
    common-merchant-jobs:
      - name: "default"
        order-statuses: [PAID, DELIVERED, FAILED, CANCELLED]
        cron: "0 */1 * * * *"
        max-count-per-execution: 30
        page-size: 10

---
spring:
  config:
    activate:
      on-profile: clustered

---
spring:
  config:
    activate:
      on-profile: ram

org:
  jobrunr:
    database:
      skip-create: true

---
spring:
  config:
    activate:
      on-profile: persistent
