logging:
  level:
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: DEBUG

server:
  shutdown: graceful

spring:
  application:
    name: 'scheduler-quartz'
  profiles:
    active:
      - ${SPRING_PROFILE_NAME:dev}
      # - persistent
      - ram
      # - streaming
      - pagination
      # - clustered
      - standalone
  quartz:
    auto-startup: true
    scheduler-name: "Demo-Quartz-Scheduler"
  lifecycle:
    timeout-per-shutdown-phase: 4m
  main:
    banner-mode: off
  mvc:
    converters:
      preferred-json-mapper: jackson
  docker:
    compose:
      enabled: true
      file: scheduler-quartz/docker-compose.yaml
  datasource:
    username: ${DB_USERNAME:dbusername}
    password: ${DB_PASSWORD:dbpassword}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_marketplace_quartz}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 5000
      validation-timeout: 2000
      leak-detection-threshold: 300000
  liquibase:
    changelog: classpath:/db/changelog/changelog.yaml
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      client-id: scheduler-comparison-quartz-1

kafka:
  topics:
    notification-platform: order-statuses-quartz.1
    loca-lola-refunds: loca-lola-refunds-quartz.1

scheduler:
  jobs:
    dedicated-merchant-jobs:
      - name: "Loca-Lola failure refunds"
        job-handler: locaLolaDedicatedJobHandler
        merchant-ids: [4]
        order-statuses: [FAILED]
        cron: "0 */1 * * * ?"
        # Since this action does not intersect with the other flow, it can be executed concurrently.
        ignored-by-common: false
        max-count-per-execution: 30
        page-size: 10
      - name: "WildFruit handler"
        job-handler: wildFruitDedicatedJobHandler
        merchant-ids: [5]
        order-statuses: [PAID, DELIVERED, FAILED, CANCELLED]
        cron: "0 */1 * * * ?"
        max-count-per-execution: 30
        page-size: 10
    common-merchant-jobs:
      - name: "default"
        job-handler: commonJobHandler
        order-statuses: [PAID, DELIVERED, FAILED, CANCELLED]
        cron: "0 */1 * * * ?"
        max-count-per-execution: 30
        page-size: 10

---
spring:
  config:
    activate:
      on-profile: clustered

  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: Quartz-Clustered
            instanceId: Quartz-Clustered-0
          jobStore:
            clusterCheckinInterval: 20000
            isClustered: true

---
spring:
  config:
    activate:
      on-profile: ram

  quartz:
    job-store-type: memory
    jdbc:
      initialize-schema: never

---
spring:
  config:
    activate:
      on-profile: persistent

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
