logging:
  level:
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: DEBUG

server:
  shutdown: graceful

spring:
  application:
    name: 'scheduler-quartz'
  profiles:
    active:
      - ${SPRING_PROFILE_NAME:dev}
  lifecycle:
    timeout-per-shutdown-phase: 4m
  main:
    banner-mode: off
  mvc:
    converters:
      preferred-json-mapper: jackson
  docker:
    compose:
      enabled: true
      file: scheduler-quartz/docker-compose.yaml
  datasource:
    username: ${DB_USERNAME:dbusername}
    password: ${DB_PASSWORD:dbpassword}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_marketplace_quartz}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 5000
      validation-timeout: 2000
      leak-detection-threshold: 300000
  liquibase:
    changelog: classpath:/db/changelog/changelog.yaml
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      client-id: scheduler-comparison-quartz-1
